---
server:
    install: '1'
    packages: [vim, git]
    timezone: Asia/Tokyo
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: jessie64, hostname: myapp-local, ip: 192.168.33.100, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www
    servername: local-myapp.com
mysql:
    install: '1'
    root_password: vagrant
    database: myapp
    user: vagrant
    password: vagrant
    dump: ''
php:
    install: '1'
#    ppa: php5-5.6
#    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-xdebug, php5-fpm, php5-curl]
    packages: [php7.1-cli, php7.1-intl, php7.1-mcrypt, php7.1-mysql, php7.1-xdebug, php7.1-fpm, php7.1-curl, php7.1-xml]

xdebug:
    install: '1'
composer:
    install: '1'

