---
- name: Install Nginx
  become: true
  apt: pkg=nginx state=latest

- name: Change default nginx site
  become: true
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx
